INSERT INTO item (name, price) VALUES ('Ananas',25.0);
INSERT INTO item (name, price) VALUES ('Gurka',17.9);
INSERT INTO item (name, price) VALUES ('Kaffe',109.0);
INSERT INTO item (name, price) VALUES ('Choklad',35.0);
INSERT INTO item (name, price) VALUES ('Te med smak av exotiska frukter',34.0);
INSERT INTO item (name, price) VALUES ('Ost',89.00);
INSERT INTO item (name, price) VALUES ('Butter',55);
INSERT INTO item (name, price) VALUES ('Levain med frukt och mandel',69.0);
INSERT INTO item (name, price) VALUES ('Kokosvatten',22.0);
INSERT INTO item (name, price) VALUES ('Apelsiner',20.0);
INSERT INTO item (name, price) VALUES ('Bananer',20.0);
INSERT INTO item (name, price) VALUES ('Potatis Amandine',28.0);